### ISSUE TITLE
Feature: @Export: add support for Enum + Flags 

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftGodot#128]
We now have the @Export in place, and would like to use this to also surface enumerations and option flags.

There is a previous discussion here:

_Originally posted by @alicerunsonfedora in https://github.com/migueldeicaza/SwiftGodot/issues/86#issuecomment-1586253254_

**Comment by alicerunsonfedora** [comment]
I have `PickerNameProvider` in the PR to bring my macro library in (#129), which should hopefully be a good starting point.

**Comment by migueldeicaza** [comment]
Thank you!   If you do not mind, I will take it and fold it into Export, so that we have a single idiom to export these elements to users (this would also align with the GDScript and C# versions that have folded those capabilities in the same attribute).

**Comment by alicerunsonfedora** [comment]
I don't think we should fold `@PickerNameProvider` into `@Export`, but rather have `@Export` utilize `@PickerNameProvider` in its expansion, such that:

```swift
@Export
enum SomeEnum: Int {
    case a, b, c
}

// expands into:
@PickerNameProvider
enum SomeEnum: Int {
	case a, b, c
}

// other expansions of @Export here
```

While `@Export` as an all-encompassing macro that handles everything for you sounds nice, I've discovered that a lot of its underlying behaviors aren't explicit, almost to a point of being magic.

Personally, I prefer to have macros, functions, etc. be explicit so that I, as a developer, can clearly understand what’s going on under the hood. While having `@Export` take on the roles `@PickerNameProvider` does may provide a good DX at first, I’m worried people will make some faulty assumptions and then get frustrated with it because it’s not obvious what it’s doing. I don’t think we should fully rely on Xcode’s expand macro behavior to handle that for us, since some folks might prefer to use other text editors.

This isn't to say I'm against using `@Export`; I think that should still be an option. However, I think that, rather than have `@Export` try to handle everything for us, we break this up into smaller, more understandable macros that `@Export` can combine together.

**Comment by migueldeicaza** [comment]
Some observations:

I do not believe I can reuse `@Export` applied to variables that could be enums, as there is no way of knowing purely from the name that we have an enum - and the macro system does not run on a resolved AST.    So I believe that we do need an `@ExportEnum` macro that we would direct users to.    

I am sad about the need of having to use an additional `@ExportEnum` macro over `@Export`, because it is another thing that needs to be explained, and there is no easy way of communicating to our users when they apply `@Export` to a variable that is backed by an enum value that they should be steered to `@ExportEnum`

I do not mind `@PickerNameProvider` or `@Export` on an enumeration definition.   I like the latter a bit more to simplify the story along  (and I have been thinking that `Callable` on methods is bad both because it can be confusing given the existence of the Godot Callable, so I am thinking maybe they should be '@Export' too).

But the above is not my main concern.

My main concern is what should the experience be if the user merely annotates the var, but not the enumeration.

So what should do we for cases like this:

```
@Godot class Demo: Node {
   enum Alphabet { case a }
   @ExportEnum letter: Alphabet
}
```

In the above case, the enum 'Alphabet' has not been flagged with `@PickerNameProvider`.

**Comment by migueldeicaza** [comment]
Proof of concept of the fix is now on a branch, details here:

https://github.com/migueldeicaza/SwiftGodot/discussions/473

**Comment by migueldeicaza** [comment]
Merged.
