### ISSUE TITLE
Specific InputEvent cast fails

### ISSUE THREAD

**Issue by BadChoice** [migueldeicaza/SwiftGodot#166]
There is no way to cast the inputEvent to any event (to get its inner variables)

```
override func _input(event: InputEvent) {
     if let e = event as? InputEventMouseButton {
      print(event)
    }
}
```

**Comment by migueldeicaza** [comment]
Mhm, this is a very interesting problem.

Going to look into this.

**Comment by migueldeicaza** [comment]
I think that a short term solution is to provide an unsafe cast operation.  Something like:

let v: InputEventMouseButton = event.cast()

because I can’t find a way of finding the most derived type given an object.   I am also afraid this would be slow.

There is a chance I can make the cast safe, but still with that ugly syntax.  Unless anyone knows of a pluggable way to cast types in Swift

**Comment by BadChoice** [comment]
The simple solution would work
Maybe I can help you as I have qide experience in swift

but I don’t really understand the problem, the boutton event inherts from eventinput right? 

What is the cause it is not the concrete type?

**Comment by tishin** [comment]
> What is the cause it is not the concrete type?

Because it's not being initialized as one. The code in question is:

```swift
func _Node_proxy_input (instance: UnsafeMutableRawPointer?, args: UnsafePointer<UnsafeRawPointer?>?, retPtr: UnsafeMutableRawPointer?) {
    guard let instance else { return }
    guard let args else { return }
    let swiftObject = Unmanaged<Node>.fromOpaque(instance).takeUnretainedValue()
    let resolved_0 = args [0]!.load (as: UnsafeRawPointer.self)
    
    swiftObject._input (event: lookupLiveObject (handleAddress: resolved_0) as? InputEvent ?? InputEvent (nativeHandle: resolved_0))
}
```

Godot is passing a pointer to abstract `InputEvent` (Godot's input event, not the swift one), and `SwiftGodot` initializes an abstract swift `InputEvent` as well, and that's why the cast to concrete type fails. I assume the solution with `.cast()` is not really about casting, but rather about creating a new object with concrete swift type using the same pointer to the C object from the abstract swift object.

**Comment by migueldeicaza** [comment]
@tishin is exactly right - thanks for the explanation.

A more complete solution is to find the "most derived type" given a pointer - but this information is not tracked by Godot's object system.   This would require introducing a new method to the base class for `Object` in Godot, and have each one of those require a unique type identifier for each registered type - so that we could get the exact type given an instance of an object.

**Comment by migueldeicaza** [comment]
I do not like my original idea of allowing any Wrapped to be converted into a subclass, that might be dangerous.   I thought "Maybe if I call this dangerousCast", but this looks to common.

I think I have a better option, a set of vetted methods that can cast to various subclasses.

**Comment by migueldeicaza** [comment]
Update: there is a get_class method that returns a string, it might be slow, but I could get the precise type information from it.

**Comment by BadChoice** [comment]
Just now I'm using this regexp to get the inner variables (that's not a solution, but can help somebody if wants to start using it while we don't find the final solution)

```
  override func _input(event: InputEvent) {
      if event.getClass() == "InputEventMouseButton" {            
          let regex = /position=\(\((\d*), (\d*)\)\)/             //https://regex101.com/r/ry8aTb/1
          if let match = event.description.firstMatch(of: regex) {
             let pressed = event.description.contains("pressed=true")
              let position = Vector2(x: Float(match.1)!, y: Float(match.2)!)
              inputDelegate?.onMouseButton(position: position, pressed:pressed)
          }
      }
```

**Comment by migueldeicaza** [comment]
A better version of the hack is:

let mb = InputEventMouseButton (nativeHandle: event.handle)

**Comment by migueldeicaza** [comment]
Well well well, it turns out that I already had the code to do the "most derived type", but I just did not use it in this codepath.

So now we have a solution that is both correct, and safe.   Your original idiom that you tried should work now.

**Comment by BadChoice** [comment]
it works! awesome!!!

**Comment by migueldeicaza** [comment]
For my own reference, this is the commit:

d9941d41decf13cc332a637257a77b9cfd66d31f
