### ISSUE TITLE
Vector3 operator error

### ISSUE THREAD

**Issue by Matt-Is-Confused** [migueldeicaza/SwiftGodot#179]
Using 0.22.0
Tested for -= += *= /=
``` Swift
aVector3 -= anotherVector3
```
results in the following error
```
error: referencing operator function '-=' on 'FloatingPoint' requires that 'Vector3' conform to 'FloatingPoint'
        rotationTarget -= rotationInput.limitLength(length: 1.0)
                       ^
Swift.FloatingPoint:1:17: note: where 'Self' = 'Vector3'
public protocol FloatingPoint : Hashable, SignedNumeric, Strideable where Self == Self.Magnitude {
                ^
error: fatalError
```

**Comment by migueldeicaza** [comment]
Our Vector types do not currently have many of the convenience functions of SIMD3 in Swift.

The source code for Swift types is here:

https://github.com/apple/swift/blob/main/stdlib/public/core/SIMDVector.swift

**Comment by migueldeicaza** [comment]
I am left wondering a few options:

1. Should I use a SIMD data type as the backing store for our Vector types instead of the raw elements?  We could get some of the performance benefits, but also, we would need to replicate all operators.
2. Should I map in the generator all uses of Vector types into Swift SIMD types, a special treatment similar to what we do with Godot String and Godot Dictionary: where we hide the Godot version behind the use of the Swift API.   This would give us all the benefits of Swift's APIs, the only downside would be dealing with all the assorted places where this is marshaled.   And the data types might be of different size, so I am not sure that we can just transparently use one over the other without the marshaling.

**Comment by Matt-Is-Confused** [comment]
Is there a possibility where marshaling back and forth over the gdext boundary could become a problem? For example non-scripting use cases where you are exposing Swift code to other users as an editor extension or library

**Comment by migueldeicaza** [comment]
I don’t think so
