### ISSUE TITLE
Bug: Enum generation produces MethodFlags.tatic instaead of MethodFlags.static

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftGodot#23]

**Comment by PadraigK** [comment]
I got curious about this one and took a look. It turns out that the prefix removal is causing this, because the prefix here is "MethodFlags" and the case is "methodFlagStatic". 

This enum (MethodFlags) is a big inconsistently named on the Godot side. At the moment the default case is prefixed with METHOD_FLAGS (plural) while the rest aren't. I would argue that either the name should be singular, and default case changed to match, or the name should stay plural and the other cases should match that. 

```
METHOD_FLAG_NORMAL
METHOD_FLAG_EDITOR
METHOD_FLAG_CONST
METHOD_FLAG_VIRTUAL
METHOD_FLAG_VARARG
METHOD_FLAG_STATIC
METHOD_FLAG_OBJECT_CORE
METHOD_FLAGS_DEFAULT   
```

To resolve our bug here, we could:

1. Just special case this one string.
2. Apply the prefix removal *before* snake casing, so we don't pull in the first letter of "static" 
3. Try to land an upstream change in Godot itself to update these to be consistent. 

I'm happy to do the PR in any case, but thought I'd see if there are any preferences on the approach (or alternatives that I haven't considered)

**Comment by PadraigK** [comment]
~3. Try to land an upstream change in Godot itself to update these to be consistent.~

I asked here https://github.com/godotengine/godot/issues/82612 but there's no appetite since it would be a compatibility breaking change.
