### ISSUE TITLE
Calling emit() on an object, only seems to deliver the signal to that object not others connected to the same signal

### ISSUE THREAD

**Issue by pcbeard** [migueldeicaza/SwiftGodot#254]
See attached project. Try running `swift TestSignals` and notice that if SpinningCube._input() is active, and ListenerNode._input() is commented out, that ListenerNode._on_pressed() never gets called. It also seems to be that if you try to use `SpinningCube.pressed` from `ListenerNode._ready()`, without also using the #signal() macro in the `ListenerNode` class, this will fail to find the signal with this error message:

```
ERROR: In Object of type 'ListenerNode': Attempt to connect nonexistent signal 'pressed' to callable 'ListenerNode::_on_pressed'.
at: connect (core/object/object.cpp:1282)
```

[HelloSwiftGodotKit.zip](https://github.com/migueldeicaza/SwiftGodot/files/13477310/HelloSwiftGodotKit.zip)

**Comment by PadraigK** [comment]
This is behaving as expected, but its understandable why anyone would see it as a bug :/ 

Godot's signal mechanism connects an instance emitting the signal to another node. This is unusual for a notification pattern which normally allows another object to globally observe a notification/signal without needing to know about the emitting instance. 

From the code in the zip file: 
```swift
@Godot
class ListenerNode: Node {
    #signal("pressed", arguments: ["event" : InputEvent.self])
    
    @Callable func _on_pressed(event: InputEvent) {
        print("event = \(event)")
    }
    
    override func _ready() {
        connect(signal: pressedSignal, to: self, method: "_on_pressed")    
    }
    
    override func _input(event: InputEvent) {
        guard event.isPressed() && !event.isEcho() else { return }
        emit(signal: pressedSignal, event)
    }
}
```

In `_ready` here, the code is attempting to connect an instance of `ListenerNode` to a signal which `ListenerNode` does not emit. 

Compared with:

```swift
    func addSpinningCube(_ pos: Vector3) {
        let n = SpinningCube()
        n.position = pos
        rootNode.addChild(node: n)
        if !listening {
            n.connect(signal: pressedSignal, to: n, method: "_on_pressed")
            listening = true
        }
    }
```

This call to connect is correct because it's connecting an instance of SpinningCube.

**Comment by pcbeard** [comment]
Yes, I see the error of my ways now. Thanks!
