### ISSUE TITLE
Update Vector3's variable type from Float to Double

### ISSUE THREAD

**Issue by Kyle-Ye** [migueldeicaza/SwiftGodot#288]
The documentation from Godot states that `Vector3.x` is a `float` type.

But the `float` type in Godot is 64 bits which corresponds to `Swift.Double`.

We are doing it right in some API eg. `void _physics_process(delta: float)` -> `_physicsProcess(delta: Double)`

And we should fix it here. Otherwise we will constantly asked by the compiler to add `Float()`
```
velocity.x = direction.x * Float(speed)
```

> CGFloat is 32 bits on 32 bits platform and 64 bits on 64 bits platform
> Swift.Float is 32 bits
> Swift.Double is 64 bits

**Comment by Kyle-Ye** [comment]
After double-checking the Godot docs, it seems to be Vector3.x should be `Double/Float` depending on whether we use `precision=double`

https://docs.godotengine.org/en/4.2/classes/class_float.html

**Comment by migueldeicaza** [comment]
It is a bit more complicated than that, sadly.   I wish we had documented that instead of having this on Slack.

Generally, the interface between Godot and the binding language is via Doubles, regardless of the internal storage (Float/Double) as you pointed out.   There is an exception for the Variant types, where the types are the size that have been configured with, in this case, Float.

It is cumbersome, but this is a requirement enforced in other places, like Variants, so we can not just change that size.

**Comment by miku1958** [comment]
Can we add a protocol like GDFloat and implement it to Double and Float, so that internally it will be Float for Vector but we can assign Float/Double to it and we can use Double and Float to operate with it without cast.
