### ISSUE TITLE
Issue with Signal Invocation in Extensions

### ISSUE THREAD

**Issue by Luminaron** [migueldeicaza/SwiftGodot#333]
I'm facing an issue where signals are not invoking methods annotated with `@Callable` within an extension. Typically, when these methods are in the main class, signal invocation functions correctly. However, in my current setup, moving `@Callable` methods to an extension results in them not being invoked by signals.

**Comment by Luminaron** [comment]
Below is a working example for this behavior. Comment and uncomment the two `invokeMethod()` to replicate.
```swift
@Godot
class SignalEmitter: Node
{
    #signal("invoke_methods")

    var shouldEmit = false

    override func _process(delta _: Double)
    {
        if shouldEmit { emit(signal: SignalEmitter.invokeMethods) }
    }
}

@Godot
class InvokeTarget: Node
{
    var signalEmitter = SignalEmitter()

    override func _ready()
    {
        addChild(node: signalEmitter)
        signalEmitter.connect(signal: SignalEmitter.invokeMethods, to: self, method: "invokeMethod")
    }

    override func _process(delta _: Double)
    {
        if Input.isActionJustPressed(action: "emit_signal") { signalEmitter.shouldEmit = true }
    }

    @Callable func invokeMethod()
    {
        GD.print("Invoked")
    }
}

extension InvokeTarget
{
    /*
     @Callable func invokeMethod()
     {
         GD.print("Invoked")
     }
     */
}
```

**Comment by tishin** [comment]
The way it works now, `@Callable` macro relies on `@Godot` macro to do method registration, and `@Godot` only works with the class declaration context it was attached to. That's why in your example `InvokeTarget` registers `invokeMethod()` when it's defined within the class declaration, but doesn't see it when it's defined in the extension.

Currently it's not possible to access parent context of the syntax node that was given to a macro (`parent` node returns nil), so I don't think `@Callable` can work in extensions (at least with the registration system we have now). I don't think we can even throw an error in the macro implementation when `@Callable` is not defined within a class declaration, because that would require access to the parent syntax of the function declaration `@Callable` is attached to.

**Comment by migueldeicaza** [comment]
@tishin is exactly right - this is by design, and we can not add support for it.
