### ISSUE TITLE
Global scope enums `rawValue` mismatch

### ISSUE THREAD

**Issue by tishin** [migueldeicaza/SwiftGodot#336]
[Global scope enums](https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#enumerations) are currently generated with `Int` as the `RawValue` type. 
There are a number of methods that don't use those enum types explicitly, but accept the underlying primitive types, e.g. [Basis.fromEuler](https://docs.godotengine.org/en/stable/classes/class_basis.html#class-basis-method-from-euler) or [Rect2.growSide](https://docs.godotengine.org/en/stable/classes/class_rect2.html#class-rect2-method-grow-side). And those methods are generated with `Int64` arguments. This results in a type mismatch not allowing direct use of the raw values:
```swift
Basis.fromEuler(euler: Vector3.zero, order: Int64(EulerOrder.xyz.rawValue))
Rect2().growSide(side: Int64(Side.top.rawValue), amount: 0)
```
Those methods that do accept enum values like `Input.isKeyPressed(keycode: Key.space)` or `Image().rotate90(direction: ClockDirection.clockwise)` also convert raw values to `Int64` under the hood.

**Comment by migueldeicaza** [comment]
Thanks for your patch.

I am a little sad that things like `growSide` are taking an int value, rather than a proper enumeration.

It would have been nice to have Rect2.growSide (.top, amount: 0)

**Comment by migueldeicaza** [comment]
I am wondering if we should undo the change in #337 and instead modify the generation of methods that are currently producing Int64 for those built-in methods to use Ints.

The reason is that it would make `Export(.enum)` work for plain enumerations, and currently, this would force people to always specify Int64 as the backing store.

![image](https://github.com/migueldeicaza/SwiftGodot/assets/36863/62b6657f-7784-4d09-9079-2ff8023b765c)

**Comment by migueldeicaza** [comment]
There was no need for it.
