### ISSUE TITLE
Not possible to make test cases for SwiftGodot

### ISSUE THREAD

**Issue by nvanfleet** [migueldeicaza/SwiftGodot#81]
I tried to make some simple tests and realized that it's not possible to even instantiate a node in a TestCase. The crash occurs when the Node tries to instantiate a StringName and then is not capable of doing that because of the not-setup GDExtension code.

IMO one of the main reasons for writing in a compiled language is to be able to write some nice tests for my code. :)

<img width="962" alt="Screenshot 2023-06-05 at 11 44 37 AM" src="https://github.com/migueldeicaza/SwiftGodot/assets/1486399/f7d5d511-1af4-41ab-aea9-a606880eb280">

**Comment by migueldeicaza** [comment]
This is a good observation.

Thinking out loud: There might be an option, using SwiftGodotKit which provides an embeddable version of Godot.  

It is another dependency though and I suspect I need to make it easy to use (it is not currently)

Another option is to look into running tests from Godot.

**Comment by alicerunsonfedora** [comment]
We could likely look into having our own testing suite similar to XCTest and the popular Gut testing suite for Godot (see https://github.com/bitwes/Gut). Though this would likely require either SwiftGodotKit, or an extension of some kind that runs these tests in the editor.

**Comment by PadraigK** [comment]
+1 for this — I wanted to be able to write some tests while hacking on SwiftGodot itself (not in an extension) and there's a similar problem where `gi` is needed for almost anything. 

The SwiftGodotKit idea seems like a good lead to me, but I think there'd need to be some refactoring because it would create a circular dependency right now. 

Is there a a way to just have `libgodot` and a tiny wrapper to get godot launched, without including `SwiftGodot`?

**Comment by tishin** [comment]
This was implemented in #211. I think it's safe to close this issue.

**Comment by migueldeicaza** [comment]
Thanks, closing.
